services:
  jupyter:
    image: kuron/miniconda3:latest
    ports:
     - "8888:8888"
    volumes:
      - .:/workspace
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
